### ISSUE TITLE
Received 2 registry entries that are unknown to this client in Java client

### ISSUE THREAD

**Issue by RumoaNoa** [onebeastchris/GeyserHacks-Fabric#15]
I'm using Java client, 1.20.1.
My server is using 1.20.1 too.
When I tried to login to my server with this mod installed, I got this message and then got disconnected.
> This is usually caused by a mismatched mod set between the client and server. See the client logs for more details.
> The following registry entry namespaces may be related:
> iaalchemy
> ofunnymusic

No log on server-side, it just says disconnected.
But there are logs on client-side.
<details><summary>Details</summary>
<p>

```
[20:05:45] [Render thread/INFO]: Connecting to [server ip and port]
[20:05:46] [Render thread/INFO]: Started 1 worker threads
[20:05:46] [Render thread/ERROR]: Received unknown remote registry entries from server
[20:05:46] [Render thread/ERROR]: Registry entry (ofunnymusic:music_disc.we_wish_you) is missing from local registry (minecraft:sound_event)
[20:05:46] [Render thread/ERROR]: Registry entry (iaalchemy:ambient.angelic) is missing from local registry (minecraft:sound_event)
[20:05:46] [Render thread/ERROR]: Registry remapping failed!
net.fabricmc.fabric.impl.registry.sync.RemapException: Received 2 registry entries that are unknown to this client.
This is usually caused by a mismatched mod set between the client and server. See the client logs for more details.
The following registry entry namespaces may be related:
iaalchemy
ofunnymusic
	at net.fabricmc.fabric.impl.registry.sync.RegistrySyncManager.checkRemoteRemap(RegistrySyncManager.java:388) ~[fabric-registry-sync-v0-2.2.6+b3afc78b77-2a2b63c9f8cdfd43.jar:?]
	at net.fabricmc.fabric.impl.registry.sync.RegistrySyncManager.apply(RegistrySyncManager.java:284) ~[fabric-registry-sync-v0-2.2.6+b3afc78b77-2a2b63c9f8cdfd43.jar:?]
	at net.fabricmc.fabric.impl.registry.sync.RegistrySyncManager.lambda$receivePacket$0(RegistrySyncManager.java:118) ~[fabric-registry-sync-v0-2.2.6+b3afc78b77-2a2b63c9f8cdfd43.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:115) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1175) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:802) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[minecraft-1.20.1-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.21.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) ~[NewLaunch.jar:?]
[20:05:46] [Render thread/INFO]: Stopping worker threads
```

</p>
</details>

As an extra, I can login with my Bedrock client.

**Comment by onebeastchris** [comment]
oh oops, i accidentally uploaded a custom hurricane build instead of the normal one to modrinth; lemme fix that rq.

**Comment by onebeastchris** [comment]
https://modrinth.com/mod/hurricane/version/1.0.2+1.20.1 please re-download this version; i uploaded the correct one. My bad!
Thanks for the issue report.
